FROM nicekiwi/aws-base:latest

# Install PHP 8.0
RUN dnf install -y php php-cli php-common php-json php-mbstring php-mysqlnd php-pdo php-xml php-zip php-gd php-xmlrpc php-soap php-opcache php-pecl-imagick php-pecl-redis php-pecl-zip